export const CHECKUP_CATEGORY_REQUEST = 'CHECKUP_CATEGORY_REQUEST'
export const CHECKUP_CATEGORY_SUCCESS = 'CHECKUP_CATEGORY_SUCCESS'
export const CHECKUP_CATEGORY_FAILURE = 'CHECKUP_CATEGORY_FAILURE'
export const CHECKUP_CATEGORY_COMPLETE = 'CHECKUP_CATEGORY_COMPLETE'
